# r code for k-NN data model


# Importing the dataset
dataset = read.csv('Social_Network_Ads.csv')
dataset = dataset[3:5]

head(dataset)

# Encoding the target feature as factor
dataset$Purchased = factor(dataset$Purchased, levels = c(0, 1))

# Splitting the dataset into the Training set and Test set
 # install.packages('caTools')
library(caTools)
set.seed(123)
split = sample.split(dataset$Purchased, SplitRatio = 0.75)
training_set = subset(dataset, split == TRUE)
test_set = subset(dataset, split == FALSE)

#dim(test_set)

# Feature Scaling
training_set[-3] = scale(training_set[-3])
test_set[-3] = scale(test_set[-3])

# Fitting K-NN to the Training set and Predicting the Test set results
library(class)

##Choosing the right K

y_pred = knn(train = training_set[, -3],
             test = test_set[, -3],
             cl = training_set[, 3],
             k=10,
             prob = TRUE)

# Making the Confusion Matrix
cm = table(test_set[, 3], y_pred)
error=(cm[1,2]+cm[2,1])/(cm[1,1]+cm[1,2]+cm[2,1]+cm[2,2])
error
accuracy=1-error


####function to get K

dat1=matrix(NA,20,2)
for(k in 1:20){
y_pred = knn(train = training_set[, -3],
             test = test_set[, -3],
             cl = training_set[, 3],
             k,
             prob = TRUE)

# Making the Confusion Matrix
cm = table(test_set[, 3], y_pred)
error=(cm[1,2]+cm[2,1])/(cm[1,1]+cm[1,2]+cm[2,1]+cm[2,2])
dat1[k,]=c(k,error)
}
plot(dat1,type='l')

####Now run the final model after know the right K that minimizes error
y_pred = knn(train = training_set[, -3],
             test = test_set[, -3],
             cl = training_set[, 3],
             k = 4,
             prob = TRUE)

# Making the Confusion Matrix
cm = table(test_set[, 3], y_pred)
error=(cm[1,2]+cm[2,1])/(cm[1,1]+cm[1,2]+cm[2,1]+cm[2,2])
accuracy=1-error



####prediction
v1=c(51,25,16)
v2=c(250000,105000,42000)
d=cbind(c(51,25,16),c(250000,105000,42000))
colnames(d)=c('Age', 'EstimatedSalary')


d2=scale(d)

y_pred = knn(train = training_set[, -3],
             test = d2,
             cl = training_set[, 3],
             k = 4,
             prob = TRUE)




# Visualising the Training set results
#install.packages("ElemStatLearn")
library(ElemStatLearn)
set = training_set
X1 = seq(min(set[, 1]) - 1, max(set[, 1]) + 1, by = 0.01)
X2 = seq(min(set[, 2]) - 1, max(set[, 2]) + 1, by = 0.01)
grid_set = expand.grid(X1, X2)
colnames(grid_set) = c('Age', 'EstimatedSalary')
y_grid = knn(train = training_set[, -3], test = grid_set, cl = training_set[, 3], k = 4)
plot(set[, -3],
     main = 'K-NN (Training set)',
     xlab = 'Age', ylab = 'Estimated Salary',
     xlim = range(X1), ylim = range(X2))
contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE)
points(grid_set, pch = '.', col = ifelse(y_grid == 1, 'springgreen3', 'tomato'))
points(set, pch = 21, bg = ifelse(set[, 3] == 1, 'green4', 'red3'))

# Visualising the Test set results
library(ElemStatLearn)
set = test_set
X1 = seq(min(set[, 1]) - 1, max(set[, 1]) + 1, by = 0.01)
X2 = seq(min(set[, 2]) - 1, max(set[, 2]) + 1, by = 0.01)
grid_set = expand.grid(X1, X2)
colnames(grid_set) = c('Age', 'EstimatedSalary')
y_grid = knn(train = training_set[, -3], test = grid_set, cl = training_set[, 3], k = 5)
plot(set[, -3],
     main = 'K-NN (Test set)',
     xlab = 'Age', ylab = 'Estimated Salary',
     xlim = range(X1), ylim = range(X2))
contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE)
points(grid_set, pch = '.', col = ifelse(y_grid == 1, 'springgreen3', 'tomato'))
points(set, pch = 21, bg = ifelse(set[, 3] == 1, 'green4', 'red3'))


